import { Inter } from "next/font/google";
import GlobalState from '@/Context/page';
import "./globals.css";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          {children}
          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
